<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="MAIN" Id="{34399180-6f2e-4cbd-9a60-f52d30bd70e9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	v : INT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[v := v+1;
PROG_ReadStructure();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>